PowerAnalysis/ViewModels/LogOnWidgetViewModel.cs
namespace HDC.PowerAnalysis.Web.ViewModels
{
	public class LogOnWidgetViewModel
	{
		public bool IsLoggedOn { get; set; }
		public string Username { get; set; }	 
	}
}

PowerAnalysis/Controllers/SessionController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AppHarbor.Web.Security;
using HDC.PowerAnalysis.Security;
using HDC.PowerAnalysis.Web.ViewModels;
using Raven.Client;
using Encryption = HDC.PowerAnalysis.Utility.Encryption;

namespace HDC.PowerAnalysis.Web.Controllers
{
	public class SessionController : Controller
    {
		private readonly IAuthenticator _authenticator;
		private readonly IDocumentSession _session;
		private const string errorMessage = "Invalid username or password";

		public SessionController(IAuthenticator authenticator, IDocumentSession session)
		{
			_authenticator = authenticator;
			_session = session;
		}

		[HttpGet]
		[AllowAnonymous]
		public ActionResult New(string returnUrl)
		{
			return View(new SessionViewModel { ReturnUrl = returnUrl });
		}

		[HttpPost]
		[AllowAnonymous]
		public ActionResult Create(SessionViewModel sessionViewModel)
		{
			User user = null;
			if (ModelState.IsValid)
			{
				user = _session.Query<User>().SingleOrDefault(x => x.Username == sessionViewModel.Username);
				if (user == null)
				{
					ModelState.AddModelError(string.Empty, errorMessage);
				}
			}

			if (ModelState.IsValid)
			{
				if (!Encryption.Verify(sessionViewModel.Password, user.Password))
				{
					ModelState.AddModelError(string.Empty, errorMessage);
				}
			}

			if (ModelState.IsValid)
			{
				_authenticator.SetCookie(user.Id, false, user.Roles.ToArray());
				var returnUrl = sessionViewModel.ReturnUrl;
				if (returnUrl != null)
				{
					Uri returnUri;
					if (Uri.TryCreate(returnUrl, UriKind.Relative, out returnUri))
					{
						return Redirect(sessionViewModel.ReturnUrl);
					}
				}

				return RedirectToAction("Index", "Home");
			}

			return View("New", sessionViewModel);
		}

		[HttpPost]
		public ActionResult Destroy()
		{
			_authenticator.SignOut();
			Session.Abandon();
			return RedirectToAction("Index", "Home");
		}

    }
}

PowerAnalysis/Controllers/UserController.cs
using System.Linq;
using System.Web.Mvc;
using AppHarbor.Web.Security;
using HDC.PowerAnalysis.Security;
using HDC.PowerAnalysis.Web.ViewModels;
using Raven.Client;
using Encryption = HDC.PowerAnalysis.Utility.Encryption;

namespace HDC.PowerAnalysis.Web.Controllers
{
	public class UserController : Controller
	{
		private readonly IAuthenticator _authenticator;
		private readonly IDocumentSession _session;
		private readonly IExecutionContext _executionContext;

		public UserController(
			IAuthenticator authenticator,
			IDocumentSession session,
			IExecutionContext executionContext)
		{
			_authenticator = authenticator;
			_session = session;
			_executionContext = executionContext;
		}

		[HttpGet]
		[AllowAnonymous]
		public ActionResult New()
		{
			return View();
		}

		[HttpPost]
		[AllowAnonymous]
		public ActionResult Create(UserInputModel userInputModel)
		{
			if (_session.Query<User>().Any(x => x.Username == userInputModel.Username))
			{
				ModelState.AddModelError("Username", "Username is already in use");
			}

			if (ModelState.IsValid)
			{
				var company = new Company(userInputModel.Username + " Co.");
				_session.Store(company);

				var user = new User(
					userInputModel.Username,
					Encryption.HashPassword(userInputModel.Password),
					new string[0],
					company);

				_session.Store(user);

				_authenticator.SetCookie(user.Id, false, user.Roles.ToArray());

				return RedirectToAction("Index", "Home");
			}

			return View("New", userInputModel);
		}

		[HttpGet]
		public ActionResult UpdatePassword()
		{
			var user = _session.Load<User>(_executionContext.UserId);
			if (user != null)
			{
				UserUpdatePasswordModel model = new UserUpdatePasswordModel()
				                                	{
				                                		Username = user.Username
				                                	};
				return View(model);
			}
			return RedirectToAction("Index", "Home");
		}

		[HttpPost]
		public ActionResult UpdatePassword(UserUpdatePasswordModel model)
		{
			var user = _session.Load<User>(_executionContext.UserId);
			if (!Encryption.Verify(model.OldPassword, user.Password))
			{
				ModelState.AddModelError("OldPassword", "Incorrect original password");
				return View("UpdatePassword", model);
			}

			if (model.NewPassword != model.ConfirmNewPassword)
			{
				ModelState.AddModelError("ConfirmNewPassword", "New password confirmation incorrect");
				return View("UpdatePassword", model);
			}

			user.ChangePassword(Encryption.HashPassword(model.NewPassword));
			return RedirectToAction("Index", "Home");
		}

		[ChildActionOnly]
		[AllowAnonymous]
		public PartialViewResult LogOnWidget()
		{
			string userName = null;
			if (!string.IsNullOrWhiteSpace(_executionContext.UserId))
			{
			}
			var user = HttpContext.User;
			bool isLoggedOn = (user != null && user.Identity != null && user.Identity.IsAuthenticated);
			if (isLoggedOn)
			{
				userName = _session.Load<User>(_executionContext.UserId).Username;
			}

			var vm = new LogOnWidgetViewModel() {IsLoggedOn = isLoggedOn, Username = userName};
			return PartialView(vm);
		}
	}
}

PowerAnalysis/Views/User/LogOnWidget.cshtml
@model HDC.PowerAnalysis.Web.ViewModels.LogOnWidgetViewModel

@{
	if (Model.IsLoggedOn) {
		@:logged in as @Model.Username
		using (Html.BeginForm("Destroy", "Session")) {
			<button type="submit">Sign out</button>
		}
	} else {
		@Html.ActionLink("log in", "New", "Session", new { returnUrl = Request.Path }, null)
		@:/ @Html.ActionLink("sign up", "New", "User")
	}
}

PowerAnalysis/Views/User/New.cshtml
@{
    ViewBag.Title = "New";
}

<h2>New</h2>
@model HDC.PowerAnalysis.Web.ViewModels.UserInputModel

@{
	ViewBag.Title = "New user";
}

<h2>New user</h2>

@using (Html.BeginForm("Create", "User")) {
	<fieldset>
		<p>
			@Html.LabelFor(x => x.Username)
			@Html.TextBoxFor(x => x.Username)
			@Html.ValidationMessageFor(x => x.Username)
		</p>

		<p>
			@Html.LabelFor(x => x.Password)
			@Html.PasswordFor(x => x.Password)
			@Html.ValidationMessageFor(x => x.Password)
		</p>

		<p>
			<button type="submit">Sign up</button>
		</p>
	</fieldset>
}

PowerAnalysis/Views/User/UpdatePassword.cshtml
@model HDC.PowerAnalysis.Web.ViewModels.UserUpdatePasswordModel

@{
    ViewBag.Title = "Update Password";
}

<h2>Update Password</h2>

@using (Html.BeginForm("UpdatePassword", "User")) {
	<fieldset>
		<p>
			@Html.LabelFor(x => x.Username)
			@Html.TextBoxFor(x => x.Username, new {@readonly="readonly"})
			@Html.ValidationMessageFor(x => x.Username)
		</p>

		<p>
			@Html.LabelFor(x => x.OldPassword)
			@Html.PasswordFor(x => x.OldPassword)
			@Html.ValidationMessageFor(x => x.OldPassword)
		</p>
		
		<p>
			@Html.LabelFor(x => x.NewPassword)
			@Html.PasswordFor(x => x.NewPassword)
			@Html.ValidationMessageFor(x => x.NewPassword)
		</p>

		<p>
			@Html.LabelFor(x => x.ConfirmNewPassword)
			@Html.PasswordFor(x => x.ConfirmNewPassword)
			@Html.ValidationMessageFor(x => x.ConfirmNewPassword)
		</p>


		<p>
			<button type="submit">Change Password</button>
		</p>
	</fieldset>
}